services:
  postgres:
    image: postgres:15-alpine
    container_name: claude-test-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: claude_test_db
      POSTGRES_USER: claude_user
      POSTGRES_PASSWORD: claude_password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - claude-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claude_user -d claude_test_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 개발용 pgAdmin (선택사항)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: claude-test-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - claude-test-network
    depends_on:
      postgres:
        condition: service_healthy

  # Redis (캐싱 및 세션 저장용, 선택사항)
  redis:
    image: redis:7-alpine
    container_name: claude-test-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - claude-test-network
    command: redis-server --appendonly yes --requirepass redis_password123

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local

networks:
  claude-test-network:
    driver: bridge
