server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/claude_test_db
    username: claude_user
    password: claude_password123
    driver-class-name: org.postgresql.Driver
    
  jackson:
    serialization:
      fail-on-empty-beans: false
    properties:
      hibernate5Module:
        feature:
          force-lazy-loading: false
          use-transient-annotation: false
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  redis:
    host: localhost
    port: 6379
    password: redis_password123
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

logging:
  level:
    com.claudetest.restaurantapi: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
    root: WARN

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 604800000 # 7 days in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method